### ISSUE TITLE
Getting Error for "useMediaQuery" being called in loop.

### ISSUE THREAD

**Issue by Sachin-chaurasiya** [ashutosh1919/react-awesome-shapes#2]
React Hook "useMediaQuery" may be executed more than once. Possibly because it is called in a loop. React Hooks must be called in the exact same order in every component render

@ashutosh1919 , please assign this to me.

**Comment by ashutosh1919** [comment]
@Sachin-chaurasiya , yes I have used it to adjust values corresponding to the breakpoint. Still, it is not the best solution. Sure, I am assigning this issue to you. You may want to approach solution like this (IMO): remove entire usage of media query. instead, find the value to use for this particular screen size. solution should be pure JS. Then, we can eleminate `react-responsive`.

**Comment by Sachin-chaurasiya** [comment]
@ashutosh1919, sure would love to work on it.
but for now,  can we go with this approach? let me know what is your thoughts.

**Comment by ashutosh1919** [comment]
@Sachin-chaurasiya , I think we should try correcting it now itself. The reason behind it (IMO) is that it will be difficult changing this once we add more functionality. It may also accumulate errors. Since, the project is in the initial stage, it will be good if we can rectify it now. Also, feel free to work in same PR. No need to create a new one.

**Comment by Sachin-chaurasiya** [comment]
@ashutosh1919, sure. will continue to work on the same PR.

**Comment by Sachin-chaurasiya** [comment]
Not happening anymore so closing it.
Feel free to open it if the issue still persists.
